#!/bin/bash
#SBATCH --job-name=segment
#SBATCH --ntasks=1
#SBATCH --mem=2G
#SBATCH --time=00:5:00

# Read Brainlife parameters from config.json
method=$(jq -r '.method' config.json)
in_files=$(jq -r '.in_files' config.json)
deskew_out_dir=$(jq -r '.deskew_out_dir' config.json)

# Call submit_job.py exactly like you would on your HPC
pip install argschema
python3 submit_job.py \
    --method "$method" \
    --deskew_tiff.deskew_out_dir "$deskew_out_dir" \
    --in_files "$in_files"




